FROM ubuntu:impish
ENV TZ="America/Los_Angeles"
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && apt-get -y install --fix-missing python3 python3-pip
ADD tests/requirements.txt /tests/requirements.txt
RUN pip3 install -r /tests/requirements.txt
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y install tzdata
ADD server /server
ADD config /config
ADD tests tests
ADD aggregator/aggregation.py /tests/
ADD aggregator/bon.py /tests/
ADD aggregator/message_encryption.py /tests/
WORKDIR /tests
CMD ./start_tests.sh
