FROM ubuntu:impish
ENV TZ="America/Los_Angeles"
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && apt-get -y install --fix-missing python3 python3-pip
ADD aggregator/requirements.txt /aggregator/requirements.txt
RUN pip3 install -r /aggregator/requirements.txt
ADD aggregator /aggregator
WORKDIR /aggregator
CMD ./start.sh
